name: 'Check GPG Keys'
description: 'Check for expired or expiring GPG keys'
inputs:
  repo-name:
    description: 'repo name'
    required: true
  github-token:
    description: 'github token for API access'
    required: true
  keyring-directory:
    description: 'path to the directory containing the keyring file'
    required: false
    default: '.blackbox'
runs:
  using: 'node16'
  main: 'dist/index.js'
